  Resources:
    ScoresTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        TableName: score
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1