  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  timeout: 900
  deploymentBucket: 
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ScoresTable, Arn]
  environment:
    TABLE_NAME: score
